site_name: Support technique
site_author: Étienne Rivard
theme:
  favicon: images/phone.png
  name: material
  language: fr
  features:
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search
  - table-reader

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

extra:
  analytics:
    provider: google
    property: G-5F4C5XCXHD

nav:
  - 'Page principale': 'index.md'
  - 'Horaire':
      - 'Groupe 1': 'horaire-groupe1.md'
      - 'Groupe 2': 'horaire-groupe2.md'
  - 'Billeterie': 'billeterie.md'
  - 'Théorie':
      - 'Résolution de problème': 'resolution-probleme.md'
      - 'Apprentissage par problème': 'apprentissage-probleme.md'
      - 'Formation des équipes': 'formation-equipes.md'
      - "Types d'utilisateurs": 'types-utilisateurs.md'
      - 'Niveaux de priorités': 'niveaux-priorites.md'
      - "Comment faire un document d'aide": 'document-aide.md'
      - 'Niveaux de service': 'niveaux-service.md'
      - 'Défis': 'defis.md'
      - 'Niveaux de support': 'niveaux-support.md'
  - 'À propos': 'apropos.md'

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

docs_dir: 'wiki'
site_dir: 'www'
use_directory_urls: True
